version: '2'

volumes:
  orderer.cogobuy.com:
  peer0.Ingdan.cogobuy.com:
  peer1.Ingdan.cogobuy.com:
  peer2.Ingdan.cogobuy.com:
  peer0.Foxsaas.cogobuy.com:
  peer1.Foxsaas.cogobuy.com:

services:

  orderer.cogobuy.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.cogobuy.com
    container_name: orderer.cogobuy.com

  peer0.Ingdan.cogobuy.com:
    container_name: peer0.Ingdan.cogobuy.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Ingdan.cogobuy.com

  peer1.Ingdan.cogobuy.com:
    container_name: peer1.Ingdan.cogobuy.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Ingdan.cogobuy.com

  peer2.Ingdan.cogobuy.com:
    container_name: peer2.Ingdan.cogobuy.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.Ingdan.cogobuy.com

  peer0.Foxsaas.cogobuy.com:
    container_name: peer0.Foxsaas.cogobuy.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Foxsaas.cogobuy.com

  peer1.Foxsaas.cogobuy.com:
    container_name: peer1.Foxsaas.cogobuy.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Foxsaas.cogobuy.com

  cli:
    container_name: cli
#    image: hyperledger/fabric-tools:$IMAGE_TAG
    image: hyperledger/fabric-tools:amd64-1.2.1-snapshot-b43fcc7
#    image: hyperledger/fabric/images/tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.Ingdan.cogobuy.com:7051
      - CORE_PEER_LOCALMSPID=IngdanMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Ingdan.cogobuy.com/users/Admin@Ingdan.cogobuy.com/msp
#      - CORE_PEER_TLS_CERT_FILE=/home/cogoadmin/go/src/github.com/hyperledger/cogobuyfabric/crypto-config/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/server.crt
#      - CORE_PEER_TLS_KEY_FILE=/home/cogoadmin/go/src/github.com/hyperledger/cogobuyfabric/crypto-config/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/server.key
#      - CORE_PEER_TLS_ROOTCERT_FILE=/home/cogoadmin/go/src/github.com/hyperledger/cogobuyfabric/crypto-config/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/ca.crt
#      - CORE_PEER_MSPCONFIGPATH=/home/cogoadmin/go/src/github.com/hyperledger/cogobuyfabric/crypto-config/peerOrganizations/Ingdan.cogobuy.com/users/Admin@Ingdan.cogobuy.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.cogobuy.com
      - peer0.Ingdan.cogobuy.com
      - peer1.Ingdan.cogobuy.com
      - peer2.Ingdan.cogobuy.com
      - peer0.Foxsaas.cogobuy.com
      - peer1.Foxsaas.cogobuy.com
