version: '2'

services:
  peer-base:
#    image: hyperledger/fabric-peer:$IMAGE_TAG
    image: hyperledger/fabric-peer:amd64-1.2.1-snapshot-b43fcc7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
#      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cogobuyfabric_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
#      - CORE_PEER_TLS_CERT_FILE=/home/cogoadmin/go/src/github.com/hyperledger/cogobuyfabric/crypto-config/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/server.crt
#      - CORE_PEER_TLS_KEY_FILE=/home/cogoadmin/go/src/github.com/hyperledger/cogobuyfabric/crypto-config/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/server.key
#      - CORE_PEER_TLS_ROOTCERT_FILE=/home/cogoadmin/go/src/github.com/hyperledger/cogobuyfabric/crypto-config/peerOrganizations/Ingdan.cogobuy.com/peers/peer0.Ingdan.cogobuy.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
